version: "3.8"

# networks:
#   vpcbr:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "10.5.0.0/16"
#           gateway: "10.5.0.1"

services:
  localstack:
    container_name: "localstack_main"
    image: "localstack/localstack"
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: bridge
    # networks:
    #   vpcbr:
    #     ipv4_address: "10.5.0.10"
  application:
    depends_on:
      - "localstack"
    container_name: "cdk_app"
    image: "node:14"
    environment:
      # - "LOCALSTACK_HOST=localhost.localstack.cloud"
      # - "LOCALSTACK_HOSTNAME=host.docker.internal"
      - "DOMAIN_NAME=${DOMAIN_NAME-}"
    volumes:
      - "$PWD/..:/app"
    stdin_open: true
    tty: true
    # extra_hosts:
    #   - "localhost.localstack.cloud:10.5.0.10"
    network_mode: bridge
    # networks:
    #   vpcbr:
    #     ipv4_address: "10.5.0.11"
